WHITE = (255, 255, 255)
RED = (186, 31, 0)

DISPLAY_WIDTH = 787
DISPLAY_HEIGHT = 786
GAME_CAPTION = "The Legend of Zelda: The Starving Link"

SCENARIO_WALKING_LIMIT_RIGHT = DISPLAY_WIDTH - 140
SCENARIO_WALKING_LIMIT_LEFT = 102
SCENARIO_WALKING_LIMIT_TOP = 90
SCENARIO_WALKING_LIMIT_DOWN = DISPLAY_HEIGHT - 150


SCORE_POS_X = DISPLAY_WIDTH - 70
SCORE_POS_Y = 20

LIVES_POS_X = DISPLAY_WIDTH - 25
LIVES_POS_Y = 150


HUNGER_BAR_POS_X = DISPLAY_WIDTH - 25
HUNGER_BAR_POS_Y = 350
HUNGER_BAR_WIDDTH = 20
HUNGER_BAR_HEIGHT = 200


APPLES_COUNT_POS_X = DISPLAY_WIDTH / 2
APPLES_COUNT_POS_Y = 8


CHICKENS_COUNT_POS_X = APPLES_COUNT_POS_X + 100
CHICKENS_COUNT_POS_Y = 8


BREADS_COUNT_POS_X = CHICKENS_COUNT_POS_X + 100
BREADS_COUNT_POS_Y = 8

STATUES_HEIGHT = 20
STATUES_WIDTH = 30

RECT_STATUE_LEFT_POS_X = SCENARIO_WALKING_LIMIT_LEFT + 5
RECT_STATUE_LEFT_POS_Y = SCENARIO_WALKING_LIMIT_TOP

RECT_STATUE_RIGHT_POS_X = SCENARIO_WALKING_LIMIT_RIGHT + 15
RECT_STATUE_RIGHT_POS_Y = SCENARIO_WALKING_LIMIT_TOP


ENEMY_1_POS = (650, 359)
ENEMY_2_POS = (97, 363)
ENEMY_3_POS = (368, 84)
ENEMY_4_POS = (375, 637)

DAMAGE_ALPHA = [i for i in range(0, 255, 50)]