BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (186, 31, 0)

DISPLAY_WIDTH = 787
DISPLAY_HEIGHT = 786
GAME_CAPTION = "The Legend of Zelda: The Starving Link"

SCENARIO_WALKING_LIMIT_RIGHT = DISPLAY_WIDTH - 140
SCENARIO_WALKING_LIMIT_LEFT = 102
SCENARIO_WALKING_LIMIT_TOP = 90
SCENARIO_WALKING_LIMIT_DOWN = DISPLAY_HEIGHT - 150


SCORE_POS_X = DISPLAY_WIDTH - 20
SCORE_POS_Y = 10

LIVES_POS_X = DISPLAY_WIDTH - 25
LIVES_POS_Y = 150


HUNGER_BAR_POS_X = DISPLAY_WIDTH - 25
HUNGER_BAR_POS_Y = 350
HUNGER_BAR_WIDDTH = 20
HUNGER_BAR_HEIGHT = 200


APPLES_COUNT_POS_X = DISPLAY_WIDTH / 2
APPLES_COUNT_POS_Y = 8


CHICKENS_COUNT_POS_X = APPLES_COUNT_POS_X + 100
CHICKENS_COUNT_POS_Y = 8


BREADS_COUNT_POS_X = CHICKENS_COUNT_POS_X + 100
BREADS_COUNT_POS_Y = 8